Added more functional to docs command
objectionary/eoc pull request #448
Opened 2024-12-25 12:51 UTC by SenjeyB

docs command now creates a directory with empry .html file for each package in the project.

2024-12-26 02:13 UTC, 0crat commented
@SenjeyB It is [not a good idea](https://www.yegor256.com/2014/04/15/github-guidelines.html) to name Git branches the way you named this one: "`main`". You've earned -12 points. Next time, better give your branch the same name as the number of the ticket that you are solving. In this case, a perfect name, for example, would be "`447`".

2025-01-27 15:48 UTC, SenjeyB commented
Hello, @yegor256! I tried to do commits for a pull request last week, but getting strange errors (last commits to this repo have the same), should I ignore them, or I can fix it?

2025-01-27 15:54 UTC, yegor256 commented
@SenjeyB is master branch clean? If not, submit a ticket blaming it for being broken. If it's clean, the problem is in your branch.

2025-01-27 19:44 UTC, SenjeyB commented
@yegor256 The master is clean, but after some testing and looking at errors I can that looks like there is a problem in the "compile" command. Also your last commit also has the same errors in these checks. Should I make a ticket for it? Or am I wrong?

2025-02-03 19:53 UTC, yegor256 commented
@SenjeyB "master is clean" means that when you build it (with `grunt`) you see no errors. If this is not the case, the master is NOT clean and you can easily report a bug. Read this: https://www.yegor256.com/2024/12/15/open-source-beginner-advice.html

2025-03-31 18:26 UTC, SenjeyB commented
@yegor256 Could you take a look on this one? After master is clean, pr looks fine

2025-04-01 02:26 UTC, yegor256 commented
@maxonfjvipon can you please review this one?

2025-04-01 08:28 UTC, maxonfjvipon requested changes

2025-04-01 08:28 UTC, maxonfjvipon commented on src/commands/docs.js
> +
@SenjeyB empty line is a code smell: https://www.yegor256.com/2014/11/03/empty-line-code-smell.html

2025-04-01 08:28 UTC, maxonfjvipon commented on src/commands/docs.js
> +    for (const xmirFile of xmirFiles) {
@SenjeyB let's rename these variables to `xmir` and `xmirs`

2025-04-01 08:28 UTC, maxonfjvipon commented on src/commands/docs.js
> +      const outputPath = path.join(outputDir, `package_${packagePath}.html`);
@SenjeyB let's try to use variables that consist of one word. It's obvious what's path and what's file. https://www.yegor256.com/2015/01/12/compound-name-is-code-smell.html

2025-04-02 10:05 UTC, maxonfjvipon commented on package.json
> +    "@eslint/js": "^9.23.0",
@SenjeyB what is this dependency for, is it used anywhere during the build?

2025-04-02 10:05 UTC, maxonfjvipon commented on src/commands/docs.js
> +function readxmirsRecursively(dir) {
@SenjeyB maybe `readXmirsRecursively`?

2025-04-02 10:06 UTC, maxonfjvipon commented on src/commands/docs.js
> +    const inputDir = path.resolve(opts.target, '.eoc', '1-parse');
@SenjeyB let's rename these variables to just `input` and `output`

2025-04-02 10:07 UTC, maxonfjvipon commented on src/commands/docs.js
> +      const output = path.join(outputDir, `package_${packages}.html`);
@SenjeyB to avoid conflict this variable may be renamed to `html`

2025-04-02 10:08 UTC, maxonfjvipon commented on test/commands/test_docs.js
> +
@SenjeyB let's remove empty lines in the tests

2025-04-02 11:50 UTC, SenjeyB commented on package.json
> +    "@eslint/js": "^9.23.0",
I added it when had some troubles after recent eslint fix

2025-04-02 13:04 UTC, maxonfjvipon approved these changes

2025-04-02 13:04 UTC, maxonfjvipon commented
@yegor256 please check

2025-04-12 20:38 UTC, SenjeyB commented
@yegor256 Can you check please?

2025-04-25 20:57 UTC, SenjeyB commented
@yegor256 Hello! Can you merge or check please? The PR is waiting for too long now, Or maybe I need to change someting here?

2025-05-05 06:40 UTC, maxonfjvipon commented
@yegor256 please check

2025-05-08 04:39 UTC, yegor256 commented
@rultor merge

2025-05-08 04:41 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/48313-2861727573).

2025-05-08 04:58 UTC, rultor commented
> @rultor merge

@senjeyb @yegor256 Oops, I failed. You can see the full log [here](https://www.rultor.com/t/48313-2861727573) (spent 15min).

```
      at checkExecSyncError (node:child_process:890:11)
      at execSync (node:child_process:962:15)
      at runSync (test/helpers.js:28:12)
      at Context.<anonymous> (test/commands/test_dataize.js:43:22)
      at process.processImmediate (node:internal/timers:476:21)
\u001b[0m
\u001b[0m  5) dataize
       dataizes with command-line argument:
\u001b[0m\u001b[31m     Error: Command failed: node /home/r/repo/src/eoc.js --batch dataize simple --clean --easy --parser=0.55.0 --home-tag=0.55.0 -s /home/r/repo/temp/test-dataize-with-arg -t /home/r/repo/temp/test-dataize-with-arg/target Hooray
\u001b[31mThe command "/home/r/repo/mvnw/mvnw eo:lint -Deo.version=0.55.0 -Deo.tag=0.55.0 --quiet -Deo.sourcesDir=/home/r/repo/temp/test-dataize-with-arg -Deo.targetDir=/home/r/repo/temp/test-dataize-with-arg/target -Deo.outputDir=/home/r/repo/temp/test-dataize-with-arg/target/classes -Deo.generatedDir=/home/r/repo/temp/test-dataize-with-arg/target/generated-sources -Deo.placed=/home/r/repo/temp/test-dataize-with-arg/target/eo-placed.csv -Deo.placedFormat=csv -Deo.failOnWarning=false --batch-mode --color=never --update-snapshots --fail-fast --strict-checksums" exited with #1 code\u001b[39m
\u001b[0m\u001b[90m
      at checkExecSyncError (node:child_process:890:11)
      at execSync (node:child_process:962:15)
      at runSync (test/helpers.js:28:12)
      at Context.<anonymous> (test/commands/test_dataize.js:76:20)
      at process.processImmediate (node:internal/timers:476:21)
\u001b[0m
\u001b[0m  6) link
       compiles a simple .EO program into an executable .JAR:
\u001b[0m\u001b[31m     Error: Command failed: node /home/r/repo/src/eoc.js --batch link --verbose --easy --parser=0.55.0 --home-tag=0.55.0 -s /home/r/repo/temp/test-link/java/src -t /home/r/repo/temp/test-link/java/target --language=Java
\u001b[31mThe command "/home/r/repo/mvnw/mvnw eo:lint -Deo.version=0.55.0 -Deo.tag=0.55.0 --errors -Deo.sourcesDir=/home/r/repo/temp/test-link/java/src -Deo.targetDir=/home/r/repo/temp/test-link/java/target -Deo.outputDir=/home/r/repo/temp/test-link/java/target/classes -Deo.generatedDir=/home/r/repo/temp/test-link/java/target/generated-sources -Deo.placed=/home/r/repo/temp/test-link/java/target/eo-placed.csv -Deo.placedFormat=csv -Deo.failOnWarning=false --batch-mode --color=never --update-snapshots --fail-fast --strict-checksums" exited with #1 code\u001b[39m
\u001b[0m\u001b[90m
      at checkExecSyncError (node:child_process:890:11)
      at execSync (node:child_process:962:15)
      at runSync (test/helpers.js:28:12)
      at link (test/commands/test_link.js:34:12)
      at Context.<anonymous> (test/commands/test_link.js:48:16)
      at process.processImmediate (node:internal/timers:476:21)
\u001b[0m
\u001b[0m  7) resolve
       resolves eo-runtime:
\u001b[0m\u001b[31m     Error: Command failed: node /home/r/repo/src/eoc.js --batch resolve --verbose --easy --parser=0.55.0 --home-tag=0.55.0 -s /home/r/repo/temp/test-resolve/src -t /home/r/repo/temp/test-resolve/target
\u001b[31mThe command "/home/r/repo/mvnw/mvnw eo:lint -Deo.version=0.55.0 -Deo.tag=0.55.0 --errors -Deo.sourcesDir=/home/r/repo/temp/test-resolve/src -Deo.targetDir=/home/r/repo/temp/test-resolve/target -Deo.outputDir=/home/r/repo/temp/test-resolve/target/classes -Deo.generatedDir=/home/r/repo/temp/test-resolve/target/generated-sources -Deo.placed=/home/r/repo/temp/test-resolve/target/eo-placed.csv -Deo.placedFormat=csv -Deo.failOnWarning=false --batch-mode --color=never --update-snapshots --fail-fast --strict-checksums" exited with #1 code\u001b[39m
\u001b[0m\u001b[90m
      at checkExecSyncError (node:child_process:890:11)
      at execSync (node:child_process:962:15)
      at runSync (test/helpers.js:28:12)
      at resolve (test/commands/test_resolve.js:28:12)
      at Context.<anonymous> (test/commands/test_resolve.js:42:16)
      at process.processImmediate (node:internal/timers:476:21)
\u001b[0m
\u001b[0m  8) test
       executes a single Java unit test:
\u001b[0m\u001b[31m     Error: Command failed: node /home/r/repo/src/eoc.js --batch test --verbose --easy --parser=0.55.0 --home-tag=0.55.0 --stack=16M --heap=128M -s /home/r/repo/temp/test-test/java/src -t /home/r/repo/temp/test-test/java/target --language=Java
\u001b[31mThe command "/home/r/repo/mvnw/mvnw eo:lint -Deo.version=0.55.0 -Deo.tag=0.55.0 --errors -Deo.sourcesDir=/home/r/repo/temp/test-test/java/src -Deo.targetDir=/home/r/repo/temp/test-test/java/target -Deo.outputDir=/home/r/repo/temp/test-test/java/target/classes -Deo.generatedDir=/home/r/repo/temp/test-test/java/target/generated-sources -Deo.placed=/home/r/repo/temp/test-test/java/target/eo-placed.csv -Deo.placedFormat=csv -Deo.failOnWarning=false --batch-mode --color=never --update-snapshots --fail-fast --strict-checksums" exited with #1 code\u001b[39m
\u001b[0m\u001b[90m
      at checkExecSyncError (node:child_process:890:11)
      at execSync (node:child_process:962:15)
      at runSync (test/helpers.js:28:12)
      at test (test/commands/test_test.js:38:12)
      at Context.<anonymous> (test/commands/test_test.js:54:16)
      at process.processImmediate (node:internal/timers:476:21)
\u001b[0m


Warning:  Use --force to continue.

Aborted due to warnings.
container 0f89a21d64a2c33e435fed5609619cf1046880a9f3e17c525bfffbf0d0514d5b is dead
Thu May  8 04:58:28 UTC 2025
```

2025-05-08 06:30 UTC, merged

2025-05-08 06:30 UTC, yegor256 commented
@SenjeyB thanks!

2025-05-08 20:47 UTC, 0crat commented
@senjeyb Thank you for your contribution! Your effort has earned you +11 points: +16 as a base reward, with a -4 deduction due to the high number of review comments (24 exceeding the 8-comment threshold). While thorough feedback is valuable, we encourage concise reviews to streamline the process. Your current balance stands at [+8](https://www.eolang.org/zerocracy/objectionary-vitals.html). Keep up the good work and [continue](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) to submit quality contributions!

<!-- Thanks for the contribution! You've earned +11 points for this: +16 as a basis; -4 for too many (24 > 8) comments that were made during review. Please, [keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) them coming. Your running balance is [+8](https://www.eolang.org/zerocracy/objectionary-vitals.html).  -->